name: Deploy Pages

on:
  push:
    branches:
      - main  # or any other branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # specify your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Upload to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # change if your build output is in a different directory
